INSERT INTO exercises (name, muscle_group, equipment) VALUES 
  ('Dips', 'Chest', 'Bodyweight'),
  ('Push-up', 'Chest', 'Bodyweight'),
  ('Muscle-up', 'Back', 'Bodyweight'),
  ('Chin-up', 'Back', 'Bodyweight'),
  ('Bulgarian Split Squat (Bodyweight)', 'Legs', 'Bodyweight'),
  ('Pistol Squat', 'Legs', 'Bodyweight'),
  ('Romanian Deadlift (Barbell)', 'Legs', 'Barbell'),
  ('Front Squat (Barbell)', 'Legs', 'Barbell'),
  ('Hip Thrust (Barbell)', 'Legs', 'Barbell'),
  ('Pendlay Row (Barbell)', 'Back', 'Barbell'),
  ('Close Grip Bench Press (Barbell)', 'Chest', 'Barbell'),
  ('Good Morning (Barbell)', 'Legs', 'Barbell'),
  ('Romanian Deadlift (Dumbbell)', 'Legs', 'Dumbbell'),
  ('Incline Dumbbell Curl', 'Arms', 'Dumbbell'),
  ('Arnold Press (Dumbbell)', 'Shoulders', 'Dumbbell'),
  ('Bulgarian Split Squat (Dumbbell)', 'Legs', 'Dumbbell'),
  ('Shrugs (Dumbbell)', 'Shoulders', 'Dumbbell'),
  ('Face Pull (Cable)', 'Shoulders', 'Cable'),
  ('Lateral Raise (Cable)', 'Shoulders', 'Cable'),
  ('Cable Crossover', 'Chest', 'Cable'),
  ('Seated Cable Row', 'Back', 'Cable'),
  ('Triceps Rope Pushdown', 'Arms', 'Cable'),
  ('Hack Squat (Machine)', 'Legs', 'Machine'),
  ('Seated Calf Raise (Machine)', 'Legs', 'Machine'),
  ('Pec Deck Fly (Machine)', 'Chest', 'Machine'),
  ('Smith Machine Squat', 'Legs', 'Machine')
ON CONFLICT DO NOTHING;